# Configuration for Release Drafter: https://github.com/release-drafter/release-drafter
# Universal template for both direct commits and PR-based workflows

# Name and tag template for releases
name-template: 'Build $RESOLVED_VERSION'
tag-template: 'build-$RESOLVED_VERSION'

# Version resolver - handles both PR labels and direct commits
version-resolver:
  major:
    labels: ['breaking', 'major']
  minor:
    labels: ['feature', 'enhancement', 'minor']
  patch:
    labels: ['fix', 'bug', 'chore', 'docs', 'style', 'refactor', 'performance', 'test', 'build', 'ci', 'dependencies']
  default: patch

# Labels to exclude from changelog
exclude-labels:
  - 'skip-changelog'
  - 'duplicate'
  - 'invalid'
  - 'wontfix'
  - 'question'
  - 'help wanted'

# Auto-labeler for direct commits (pattern matching on titles)
autolabeler:
  - label: 'breaking'
    title:
      - '/breaking|major/i'
  - label: 'feature'
    title:
      - '/feat|feature|add|implement/i'
  - label: 'fix'
    title:
      - '/fix|bug|issue|resolve/i'
  - label: 'docs'
    title:
      - '/doc|readme|comment|documentation/i'
  - label: 'chore'
    title:
      - '/chore|update|bump|build|maintenance/i'
  - label: 'refactor'
    title:
      - '/refactor|cleanup|reorganize/i'
  - label: 'test'
    title:
      - '/test|testing|spec/i'
  - label: 'style'
    title:
      - '/style|format|lint/i'
  - label: 'performance'
    title:
      - '/perf|performance|optimize/i'
  - label: 'ci'
    title:
      - '/ci|workflow|action|github/i'
  - label: 'dependencies'
    title:
      - '/dep|dependencies|upgrade|package/i'

# Categories for changes (works for both PRs and auto-labeled commits)
categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'new-feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
      - 'bugfix'
  - title: '📖 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🎨 Code Style & Formatting'
    labels:
      - 'style'
      - 'formatting'
  - title: '♻️ Code Refactoring'
    labels:
      - 'refactor'
      - 'refactoring'
  - title: '⚡ Performance Improvements'
    labels:
      - 'performance'
      - 'optimization'
  - title: '✅ Tests'
    labels:
      - 'test'
      - 'testing'
  - title: '🔧 Build System & CI/CD'
    labels:
      - 'build'
      - 'ci'
      - 'cd'
      - 'workflow'
  - title: '📦 Dependencies'
    labels:
      - 'dependencies'
      - 'deps'
  - title: '🧹 Maintenance & Chores'
    labels:
      - 'chore'
      - 'maintenance'
  - title: '⏪ Reverts'
    labels:
      - 'revert'
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking'
      - 'breaking-change'
      - 'major'
  - title: '🔒 Security'
    labels:
      - 'security'
  - title: '📝 Other Changes'
    labels: []

# Template that works for both workflows
template: |
  ## What's Changed in this Build

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

  ---
  
  **Build Information:**
  - Generated: ${{ DATE }}
  - Full Changelog: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...build-$RESOLVED_VERSION

# Change template that handles both PRs and direct commits
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

# Fallback template for commits without PR numbers
no-changes-template: |
  - No labeled changes in this release

# Character escaping
change-title-escapes: '\<*_&'

# Include pre-releases in version calculation
include-pre-releases: false

# Sort direction
sort-direction: ascending
