# Configuration for Release Drafter: https://github.com/release-drafter/release-drafter

# Name and tag template for the new build release
name-template: 'Build $RESOLVED_VERSION'
tag-template: 'build-$RESOLVED_VERSION'

# Version resolver - uses patch for all changes since this is build-focused
version-resolver:
  default: patch

# Labels to exclude from changelog
exclude-labels:
  - 'skip-changelog'
  - 'duplicate'
  - 'invalid'
  - 'wontfix'

# Auto-labeler for direct commits (basic pattern matching)
autolabeler:
  - label: 'fix'
    title:
      - '/fix|bug|issue/i'
  - label: 'feature'
    title:
      - '/feat|feature|add/i'
  - label: 'docs'
    title:
      - '/doc|readme|comment/i'
  - label: 'chore'
    title:
      - '/chore|update|bump|build/i'

# Categories for changes, based on PR labels
categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '📖 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🎨 Code Style & Formatting'
    labels:
      - 'style'
  - title: '♻️ Code Refactoring'
    labels:
      - 'refactor'
  - title: '⚡ Performance Improvements'
    labels:
      - 'performance'
  - title: '✅ Tests'
    labels:
      - 'test'
      - 'testing'
  - title: '🔧 Build System & CI/CD'
    labels:
      - 'build'
      - 'ci'
  - title: '📦 Dependencies'
    labels:
      - 'dependencies'
  - title: '🧹 Maintenance & Chores'
    labels:
      - 'chore'
  - title: '⏪ Reverts'
    labels:
      - 'revert'
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking'
  - title: '📝 Other Changes'
    labels: []

# Template for the release notes body (simplified to avoid $COMMITS issues)
template: |
  ## What's Changed in this Build

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

# Change template for individual changes
change-template: '- $TITLE @$AUTHOR'
change-title-escapes: '\<*_&'
