[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_preprocessors = [
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](https://github.com/{{ remote.owner }}/{{ remote.repo }}/issues/${2}))"},
]

commit_parsers = [
    { message = "^feat", group = "🚀 Features"},
    { message = "^fix", group = "🐛 Bug Fixes"},
    { message = "^doc", group = "📚 Documentation"},
    { message = "^perf", group = "⚡ Performance"},
    { message = "^refactor", group = "♻️ Refactor"},
    { message = "^style", group = "🎨 Styling"},
    { message = "^test", group = "🧪 Testing"},
    { message = "^chore\\(release\\):", skip = true},
    { message = "^chore", group = "⚙️ Miscellaneous Tasks"},
    { message = "^build", group = "🔨 Build System"},
    { message = "^ci", group = "🤖 Continuous Integration"},
    { body = ".*security", group = "🔒 Security"},
    { message = ".*", group = "📝 Other Changes"},  # Catch-all for non-conventional commits
]

protect_breaking_commits = true
filter_commits = false
tag_pattern = "build-*"  # More flexible pattern
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "newest"  # Show newest first
